import type { NodeDef, EndpointDef, FieldDef, SecurityDef } from './types.js';
import { toPascalCase, fieldPropKey, fieldTypePropKey, defaultTypeStr } from './utils.js';

// ============================================================
// Generate the Node-RED runtime .js file
// ============================================================

export function generateRuntime(nodeDef: NodeDef, nodeName: string): string {
  const Pascal = toPascalCase(nodeName);
  return [
    `// Auto-generated by node-red-nodegen-openapi. Do not edit manually.`,
    `'use strict';`,
    ``,
    `const axios    = require('axios');`,
    `const FormData = require('form-data');`,
    `const fs       = require('fs');`,
    `const https    = require('https');`,
    ``,
    `module.exports = function(RED) {`,
    ``,
    genAuthConfigNode(nodeName, Pascal, nodeDef.security),
    ``,
    genMainNode(nodeName, Pascal, nodeDef),
    ``,
    `};`,
  ].join('\n');
}

// ============================================================
// Auth Config Node
// ============================================================

function genAuthConfigNode(nodeName: string, Pascal: string, security: SecurityDef[]): string {
  const lines: string[] = [];
  lines.push(`  // ----- Auth Config Node -----`);
  lines.push(`  function ${Pascal}AuthConfigNode(config) {`);
  lines.push(`    RED.nodes.createNode(this, config);`);
  lines.push(`  }`);
  lines.push(`  RED.nodes.registerType('${nodeName}-auth-config', ${Pascal}AuthConfigNode, {`);
  lines.push(`    credentials: { apiKey: { type: 'password' } },`);
  lines.push(`  });`);
  return lines.join('\n');
}

// ============================================================
// Main Node
// ============================================================

function genMainNode(nodeName: string, Pascal: string, nodeDef: NodeDef): string {
  const lines: string[] = [];
  lines.push(`  // ----- Main Node -----`);
  lines.push(`  function ${Pascal}Node(config) {`);
  lines.push(`    RED.nodes.createNode(this, config);`);
  lines.push(`    const node = this;`);
  lines.push(``);
  lines.push(`    node.on('input', function(msg, send, done) {`);
  lines.push(`      const authNode = RED.nodes.getNode(config.authConfig);`);
  lines.push(`      const endpoint = config.endpoint;`);
  lines.push(`      const baseUrl  = '${nodeDef.serverUrl}';`);
  lines.push(``);
  lines.push(`      let method, url, requestData;`);
  lines.push(`      const params  = {};`);
  lines.push(`      const headers = {};`);
  lines.push(``);
  lines.push(genAuthBlock(nodeDef.security));
  lines.push(``);
  lines.push(genEndpointSwitch(nodeDef.endpoints));
  lines.push(``);
  lines.push(genAxiosCall());
  lines.push(`    });`);
  lines.push(`  }`);
  lines.push(``);
  lines.push(`  RED.nodes.registerType('${nodeName}', ${Pascal}Node);`);
  return lines.join('\n');
}

// ============================================================
// Auth block: apply API key to header or query
// ============================================================

function genAuthBlock(security: SecurityDef[]): string {
  if (security.length === 0) return `      // No security schemes defined.`;

  const headerSchemes = security.filter(s => s.in === 'header');
  const querySchemes  = security.filter(s => s.in === 'query');

  const lines: string[] = [];
  lines.push(`      // Apply authentication`);
  lines.push(`      if (authNode && authNode.credentials && authNode.credentials.apiKey) {`);
  lines.push(`        const apiKey = authNode.credentials.apiKey;`);

  if (querySchemes.length > 0) {
    lines.push(`        if (authNode.scheme === '${querySchemes[0].name}') {`);
    lines.push(`          params['${querySchemes[0].keyName}'] = apiKey;`);
    if (headerSchemes.length > 0) {
      lines.push(`        } else {`);
      lines.push(`          headers['${headerSchemes[0].keyName}'] = apiKey;`);
    }
    lines.push(`        }`);
  } else if (headerSchemes.length > 0) {
    lines.push(`        headers['${headerSchemes[0].keyName}'] = apiKey;`);
  }

  lines.push(`      }`);
  return lines.join('\n');
}

// ============================================================
// Endpoint switch block
// ============================================================

function genEndpointSwitch(endpoints: EndpointDef[]): string {
  const lines: string[] = [];
  endpoints.forEach((ep, i) => {
    const kw = i === 0 ? 'if' : '} else if';
    lines.push(`      ${kw} (endpoint === '${ep.operationId}') {`);
    lines.push(genEndpointBlock(ep));
  });
  lines.push(`      } else {`);
  lines.push(`        done(new Error('Unknown endpoint: ' + endpoint));`);
  lines.push(`        return;`);
  lines.push(`      }`);
  return lines.join('\n');
}

function genEndpointBlock(ep: EndpointDef): string {
  const lines: string[] = [];
  const ind = '        '; // 8 spaces

  lines.push(`${ind}method = '${ep.method}';`);

  // Build URL (substitute path parameters)
  lines.push(`${ind}url = baseUrl + '${ep.path}';`);
  const pathFields = ep.fields.filter(f => f.location === 'path');
  for (const f of pathFields) {
    const key = fieldPropKey(ep.operationId, f.name);
    const keyType = fieldTypePropKey(ep.operationId, f.name);
    lines.push(`${ind}const _${key} = RED.util.evaluateNodeProperty(config['${key}'], config['${keyType}'] || 'str', node, msg);`);
    lines.push(`${ind}url = url.replace('{${f.name}}', encodeURIComponent(String(_${key})));`);
  }

  // Header parameters
  const headerFields = ep.fields.filter(f => f.location === 'header');
  for (const f of headerFields) {
    const key = fieldPropKey(ep.operationId, f.name);
    const keyType = fieldTypePropKey(ep.operationId, f.name);
    lines.push(`${ind}const _${key} = RED.util.evaluateNodeProperty(config['${key}'], config['${keyType}'] || 'str', node, msg);`);
    lines.push(`${ind}if (_${key} !== undefined && _${key} !== null && String(_${key}) !== '') headers['${f.name}'] = String(_${key});`);
  }

  // Query parameters
  const queryFields = ep.fields.filter(f => f.location === 'query');
  for (const f of queryFields) {
    const key = fieldPropKey(ep.operationId, f.name);
    const keyType = fieldTypePropKey(ep.operationId, f.name);
    lines.push(`${ind}const _${key} = RED.util.evaluateNodeProperty(config['${key}'], config['${keyType}'] || 'str', node, msg);`);
    lines.push(`${ind}if (_${key} !== undefined && _${key} !== null) params['${f.name}'] = _${key};`);
  }

  // Body
  const bodyFields = ep.fields.filter(f => f.location === 'body');
  if (bodyFields.length > 0) {
    /**
     *  TODO: Refactor in the future. The logic below works for now but is ad-hoc.
     *   - Most cases can be handled by genJsonBody.
     *   - Other cases need to cover:
     *     - multipart/form-data
     *     - requestBody with a single binary field
     */
    if (ep.contentType === 'multipart/form-data') {
      lines.push(...genMultipartBody(ep.operationId, bodyFields, ind));
    } else if (bodyFields.length === 1 && bodyFields[0].type === 'binary') {
      lines.push(...genRawBody(ep.operationId, bodyFields[0], ind));
    } else {
      lines.push(...genJsonBody(ep.operationId, bodyFields, ind));
    }
  }

  return lines.join('\n');
}

// ============================================================
// JSON body builder
// ============================================================

function genJsonBody(operationId: string, fields: FieldDef[], ind: string): string[] {
  const lines: string[] = [];
  lines.push(`${ind}const _body = {};`);
  for (const f of fields) {
    const key = fieldPropKey(operationId, f.name);
    if (f.type === 'enum') {
      lines.push(`${ind}_body['${f.name}'] = config['${key}'];`);
    } else {
      const keyType = fieldTypePropKey(operationId, f.name);
      const defType = defaultTypeStr(f.type);
      lines.push(`${ind}_body['${f.name}'] = RED.util.evaluateNodeProperty(config['${key}'], config['${keyType}'] || '${defType}', node, msg);`);
    }
  }
  lines.push(`${ind}requestData = _body;`);
  lines.push(`${ind}headers['Content-Type'] = 'application/json';`);
  return lines;
}

// ============================================================
// Raw body builder (binary stream or plain string)
// ============================================================

function genRawBody(operationId: string, field: FieldDef, ind: string): string[] {
  const key = fieldPropKey(operationId, field.name);
  const keyType = fieldTypePropKey(operationId, field.name);
  const lines: string[] = [];
  lines.push(`${ind}const _${key} = RED.util.evaluateNodeProperty(config['${key}'], config['${keyType}'] || 'str', node, msg);`);
  lines.push(`${ind}if (_${key} !== undefined && _${key} !== null && _${key} !== '') {`);
  if (field.type === 'binary') {
    lines.push(`${ind}  requestData = typeof _${key} === 'string' ? fs.createReadStream(_${key}) : _${key};`);
  } else {
    lines.push(`${ind}  requestData = _${key};`);
  }
  lines.push(`${ind}}`);
  return lines;
}

// ============================================================
// Multipart/form-data body builder
// ============================================================

function genMultipartBody(operationId: string, fields: FieldDef[], ind: string): string[] {
  const lines: string[] = [];
  lines.push(`${ind}const _fd = new FormData();`);
  for (const f of fields) {
    const key = fieldPropKey(operationId, f.name);
    if (f.type === 'enum') {
      lines.push(`${ind}if (config['${key}']) _fd.append('${f.name}', config['${key}']);`);
    } else if (f.type === 'binary') {
      const keyType = fieldTypePropKey(operationId, f.name);
      lines.push(`${ind}const _${key} = RED.util.evaluateNodeProperty(config['${key}'], config['${keyType}'] || 'str', node, msg);`);
      lines.push(`${ind}if (_${key} !== undefined && _${key} !== null && _${key} !== '') {`);
      lines.push(`${ind}  if (typeof _${key} === 'string') {`);
      lines.push(`${ind}    const _${key}_basename = require('path').basename(_${key});`);
      lines.push(`${ind}    _fd.append('${f.name}', fs.createReadStream(_${key}), { filename: _${key}_basename });`);
      lines.push(`${ind}  } else {`);
      lines.push(`${ind}    _fd.append('${f.name}', _${key}, { filename: 'upload', contentType: 'application/octet-stream' });`);
      lines.push(`${ind}  }`);
      lines.push(`${ind}}`);
    } else {
      const keyType = fieldTypePropKey(operationId, f.name);
      const defType = defaultTypeStr(f.type);
      lines.push(`${ind}const _${key} = RED.util.evaluateNodeProperty(config['${key}'], config['${keyType}'] || '${defType}', node, msg);`);
      lines.push(`${ind}if (_${key} !== undefined && _${key} !== null && String(_${key}) !== '') _fd.append('${f.name}', String(_${key}));`);
    }
  }
  lines.push(`${ind}requestData = _fd;`);
  lines.push(`${ind}Object.assign(headers, _fd.getHeaders());`);
  return lines;
}

// ============================================================
// Axios call with TLS / proxy / redirects
// ============================================================

function genAxiosCall(): string {
  return `
      // Build axios config
      const _axiosOpts = {
        method,
        url,
        headers,
        maxRedirects: config.followRedirects ? (parseInt(config.maxRedirects) || 5) : 0,
      };
      if (requestData !== undefined) _axiosOpts.data = requestData;
      if (Object.keys(params).length > 0) _axiosOpts.params = params;

      // TLS / SSL
      const _tlsNode = RED.nodes.getNode(config.tlsConfig);
      if (_tlsNode) {
        const _tlsOpts = {};
        _tlsNode.addTLSOptions(_tlsOpts);
        _axiosOpts.httpsAgent = new https.Agent(_tlsOpts);
      }

      // Proxy
      const _proxyUrl = config.proxy || process.env.HTTPS_PROXY || process.env.HTTP_PROXY;
      if (_proxyUrl) {
        try {
          const _pu = new URL(_proxyUrl);
          _axiosOpts.proxy = {
            protocol: _pu.protocol.slice(0, -1),
            host:     _pu.hostname,
            port:     parseInt(_pu.port || (_pu.protocol === 'https:' ? '443' : '80')),
          };
          if (_pu.username) {
            _axiosOpts.proxy.auth = { username: _pu.username, password: decodeURIComponent(_pu.password) };
          }
        } catch (e) {
          node.warn('Invalid proxy URL: ' + _proxyUrl);
        }
      }

      axios(_axiosOpts)
        .then(function(res) {
          node.status({ fill: 'green', shape: 'dot', text: String(res.status) });
          msg.payload       = res.data;
          msg.statusCode    = res.status;
          msg.responseHeaders = res.headers;
          send(msg);
          done();
        })
        .catch(function(err) {
          node.status({ fill: 'red', shape: 'ring', text: err.message });
          if (err.response) {
            msg.payload       = err.response.data;
            msg.statusCode    = err.response.status;
            msg.responseHeaders = err.response.headers;
            send(msg);
            done();
          } else {
            done(err);
          }
        });`;
}
