import type { NodeDef, EndpointDef, FieldDef, SecurityDef, CliOptions } from './types.js';
import { fieldPropKey, fieldTypePropKey, defaultTypeStr } from './utils.js';

// ============================================================
// Generate the Node-RED editor .html file
// ============================================================

export function generateHtml(nodeDef: NodeDef, nodeName: string, opts: CliOptions): string {
  return [
    `<!-- Auto-generated by node-red-nodegen-openapi. Do not edit manually. -->`,
    ``,
    genAuthConfigHtml(nodeName, nodeDef.security),
    ``,
    genMainNodeHtml(nodeName, nodeDef, opts),
  ].join('\n');
}

// ============================================================
// Auth Config Node HTML
// ============================================================

function genAuthConfigHtml(nodeName: string, security: SecurityDef[]): string {
  const configNodeType = `${nodeName}-auth-config`;
  const schemeOptions = security
    .map(s => `      <option value="${s.name}">${s.in === 'header' ? 'Header' : 'Query'}: ${s.keyName}</option>`)
    .join('\n');

  return [
    `<!-- ===== Auth Config Node ===== -->`,
    `<script type="text/html" data-template-name="${configNodeType}">`,
    `  <div class="form-row">`,
    `    <label for="node-config-input-name"><i class="fa fa-tag"></i> Name</label>`,
    `    <input type="text" id="node-config-input-name" placeholder="Name">`,
    `  </div>`,
    security.length > 1 ? [
      `  <div class="form-row">`,
      `    <label for="node-config-input-scheme"><i class="fa fa-key"></i> Scheme</label>`,
      `    <select id="node-config-input-scheme" style="width:70%">`,
      schemeOptions,
      `    </select>`,
      `  </div>`,
    ].join('\n') : '',
    `  <div class="form-row">`,
    `    <label for="node-config-input-apiKey"><i class="fa fa-lock"></i> API Key</label>`,
    `    <input type="password" id="node-config-input-apiKey" placeholder="API Key">`,
    `  </div>`,
    `</script>`,
    ``,
    `<script type="text/html" data-help-name="${configNodeType}">`,
    `  <p>Authentication configuration for the <b>${nodeName}</b> node.</p>`,
    `</script>`,
    ``,
    `<script type="text/javascript">`,
    `  RED.nodes.registerType('${configNodeType}', {`,
    `    category: 'config',`,
    `    defaults: {`,
    `      name:   { value: '' },`,
    security.length > 1 ? `      scheme: { value: '${security[0].name}' },` : '',
    `    },`,
    `    credentials: { apiKey: { type: 'password' } },`,
    `    label: function() { return this.name || '${nodeName} auth'; },`,
    `  });`,
    `</script>`,
  ].filter(l => l !== '').join('\n');
}

// ============================================================
// Main Node HTML
// ============================================================

function genMainNodeHtml(nodeName: string, nodeDef: NodeDef, opts: CliOptions): string {
  const color = opts.color ? `#${opts.color}` : '#87A980';
  const icon  = opts.icon  ? opts.icon        : 'font-awesome/fa-cloud';

  return [
    `<!-- ===== Main Node ===== -->`,
    `<script type="text/html" data-template-name="${nodeName}">`,
    genTemplate(nodeName, nodeDef),
    `</script>`,
    ``,
    `<script type="text/html" data-help-name="${nodeName}">`,
    `  <p>${nodeDef.description ?? nodeDef.title}</p>`,
    `  <p>Select an endpoint from the dropdown, fill in the fields, and send a message to trigger the API call.</p>`,
    `  <h3>Output</h3>`,
    `  <dl class="message-properties">`,
    `    <dt>payload</dt><dd>Response body from the API.</dd>`,
    `    <dt>statusCode</dt><dd>HTTP status code.</dd>`,
    `    <dt>responseHeaders</dt><dd>Response headers.</dd>`,
    `  </dl>`,
    `</script>`,
    ``,
    `<script type="text/javascript">`,
    genRegistration(nodeName, nodeDef, color, icon, opts.category),
    `</script>`,
  ].join('\n');
}

// ============================================================
// Edit dialog template
// ============================================================

function genTemplate(nodeName: string, nodeDef: NodeDef): string {
  const lines: string[] = [];

  // Node name
  lines.push(`  <div class="form-row">`);
  lines.push(`    <label for="node-input-name"><i class="fa fa-tag"></i> Name</label>`);
  lines.push(`    <input type="text" id="node-input-name" placeholder="Name">`);
  lines.push(`  </div>`);

  // Endpoint selector
  lines.push(`  <div class="form-row">`);
  lines.push(`    <label for="node-input-endpoint"><i class="fa fa-plug"></i> Endpoint</label>`);
  lines.push(`    <select id="node-input-endpoint" style="width:70%">`);
  for (const ep of nodeDef.endpoints) {
    lines.push(`      <option value="${ep.operationId}">${ep.method.toUpperCase()} ${ep.path}</option>`);
  }
  lines.push(`    </select>`);
  lines.push(`  </div>`);

  // Per-endpoint field rows
  for (const ep of nodeDef.endpoints) {
    lines.push(``);
    lines.push(`  <!-- Fields: ${ep.method.toUpperCase()} ${ep.path} -->`);
    for (const f of ep.fields) {
      lines.push(genFieldRow(ep.operationId, f));
    }
  }

  // Common settings separator
  lines.push(``);
  lines.push(`  <hr>`);

  // Auth config
  lines.push(`  <div class="form-row">`);
  lines.push(`    <label for="node-input-authConfig"><i class="fa fa-key"></i> Auth</label>`);
  lines.push(`    <input type="text" id="node-input-authConfig">`);
  lines.push(`  </div>`);

  // TLS config
  lines.push(`  <div class="form-row">`);
  lines.push(`    <label for="node-input-tlsConfig"><i class="fa fa-lock"></i> TLS</label>`);
  lines.push(`    <input type="text" id="node-input-tlsConfig">`);
  lines.push(`  </div>`);

  // Proxy
  lines.push(`  <div class="form-row">`);
  lines.push(`    <label for="node-input-proxy"><i class="fa fa-exchange"></i> Proxy</label>`);
  lines.push(`    <input type="text" id="node-input-proxy" placeholder="http://proxy:8080 (or leave blank)">`);
  lines.push(`  </div>`);

  // Follow redirects
  lines.push(`  <div class="form-row">`);
  lines.push(`    <label>&nbsp;</label>`);
  lines.push(`    <input type="checkbox" id="node-input-followRedirects" style="display:inline-block; width:auto; margin-right:5px">`);
  lines.push(`    <label for="node-input-followRedirects" style="width:auto">Follow redirects</label>`);
  lines.push(`    <span style="margin-left:10px">max:</span>`);
  lines.push(`    <input type="number" id="node-input-maxRedirects" min="0" max="20" style="width:60px; margin-left:5px">`);
  lines.push(`  </div>`);

  return lines.join('\n');
}

// ============================================================
// Individual field row
// ============================================================

function genFieldRow(operationId: string, field: FieldDef): string {
  const key     = fieldPropKey(operationId, field.name);
  const keyType = fieldTypePropKey(operationId, field.name);
  const label   = field.required
    ? `${field.name} <span style="color:red" title="required">*</span>`
    : field.name;
  const tip     = field.description ? ` title="${field.description.replace(/"/g, '&quot;')}"` : '';

  const lines: string[] = [];
  lines.push(`  <div class="form-row ep-field-row" data-endpoint="${operationId}" style="display:none"${tip}>`);
  lines.push(`    <label for="node-input-${key}">${label}</label>`);

  if (field.type === 'enum' && field.enumValues) {
    lines.push(`    <select id="node-input-${key}" style="width:70%">`);
    for (const v of field.enumValues) {
      lines.push(`      <option value="${v}">${v}</option>`);
    }
    lines.push(`    </select>`);
  } else {
    const placeholder = field.description
      ? field.description.slice(0, 60)
      : field.name;
    lines.push(`    <input type="text" id="node-input-${key}" placeholder="${placeholder}" style="width:68%">`);
    lines.push(`    <input type="hidden" id="node-input-${keyType}">`);
  }

  lines.push(`  </div>`);

  // For array-of-string: editableList container (shown only in list mode)
  if (field.type === 'array-of-string') {
    lines.push(`  <div class="form-row ep-field-row array-list-row" data-endpoint="${operationId}" data-for="${key}" style="display:none">`);
    lines.push(`    <label>&nbsp;</label>`);
    lines.push(`    <ol id="${key}-list" style="width:70%;"></ol>`);
    lines.push(`    <div style="margin-left:105px; margin-top:4px;">`);
    lines.push(`      <a href="#" id="${key}-list-add" style="font-size:0.85em"><i class="fa fa-plus"></i> Add item</a>`);
    lines.push(`    </div>`);
    lines.push(`  </div>`);
  }

  return lines.join('\n');
}

// ============================================================
// RED.nodes.registerType(...) script block
// ============================================================

function genRegistration(nodeName: string, nodeDef: NodeDef, color: string, icon: string, category: string): string {
  const defaults = genDefaults(nodeName, nodeDef);
  const typedInputInits = genTypedInputInits(nodeDef.endpoints);

  return [
    `  RED.nodes.registerType('${nodeName}', {`,
    `    category:     '${category}',`,
    `    color:        '${color}',`,
    `    defaults: {`,
    defaults,
    `    },`,
    `    inputs:  1,`,
    `    outputs: 1,`,
    `    icon:    '${icon}',`,
    `    label:   function() { return this.name || '${nodeName}'; },`,
    `    oneditprepare: function() {`,
    `      // Show/hide field rows based on selected endpoint`,
    `      function _updateFields() {`,
    `        var ep = $('#node-input-endpoint').val();`,
    `        $('.ep-field-row').hide();`,
    `        $('.ep-field-row[data-endpoint="' + ep + '"]').show();`,
    `        // Re-apply list mode visibility for array-of-string fields`,
    `        $('.array-list-row').each(function() {`,
    `          var forKey = $(this).data('for');`,
    `          var t = $('#node-input-' + forKey + 'Type').val() || 'list';`,
    `          var fieldVisible = $('#node-input-' + forKey).closest('.ep-field-row').is(':visible');`,
    `          if (t === 'list' && fieldVisible) { $(this).show(); } else { $(this).hide(); }`,
    `        });`,
    `      }`,
    `      $('#node-input-endpoint').on('change', _updateFields);`,
    `      _updateFields();`,
    ``,
    `      // typedInput widgets`,
    typedInputInits,
    `    },`,
    `    oneditsave: function() {`,
    `      $('.array-list-row').each(function() {`,
    `        var forKey = $(this).data('for');`,
    `        if ($('#node-input-' + forKey + 'Type').val() !== 'list') return;`,
    `        var items = [];`,
    `        $(this).find('ol').editableList('items').each(function() {`,
    `          var v = $(this).find('.aoi-val').val();`,
    `          if (v !== undefined && v !== null && String(v).trim() !== '') items.push(String(v).trim());`,
    `        });`,
    `        var _el = document.getElementById('node-input-' + forKey);`,
    `        if (_el) _el.value = JSON.stringify(items);`,
    `      });`,
    `    },`,
    `  });`,
  ].join('\n');
}

// ============================================================
// defaults object entries
// ============================================================

function genDefaults(nodeName: string, nodeDef: NodeDef): string {
  const lines: string[] = [];
  const ind = '      ';

  lines.push(`${ind}name:           { value: '' },`);
  lines.push(`${ind}endpoint:       { value: '${nodeDef.endpoints[0]?.operationId ?? ''}' },`);
  lines.push(`${ind}authConfig:     { value: '', type: '${nodeName}-auth-config', required: false },`);
  lines.push(`${ind}tlsConfig:      { value: '', type: 'tls-config', required: false },`);
  lines.push(`${ind}followRedirects:{ value: true },`);
  lines.push(`${ind}maxRedirects:   { value: 5 },`);
  lines.push(`${ind}proxy:          { value: '' },`);

  for (const ep of nodeDef.endpoints) {
    for (const f of ep.fields) {
      const key     = fieldPropKey(ep.operationId, f.name);
      const keyType = fieldTypePropKey(ep.operationId, f.name);
      const defVal  = f.type === 'enum'
        ? (f.enumValues?.[0] ?? '')
        : (f.default !== undefined ? String(f.default) : '');

      if (f.type === 'enum') {
        lines.push(`${ind}${key}: { value: '${defVal}' },`);
      } else {
        const defType = defaultTypeStr(f.type);
        const defValue = f.type === 'array-of-string' ? '[]' : defVal;
        lines.push(`${ind}${key}:     { value: '${defValue}' },`);
        lines.push(`${ind}${keyType}: { value: '${defType}' },`); // list | msg | flow
      }
    }
  }

  return lines.join('\n');
}

// ============================================================
// typedInput initialization calls (inside oneditprepare)
// ============================================================

function genTypedInputInits(endpoints: EndpointDef[]): string {
  const lines: string[] = [];
  const ind = '      ';

  for (const ep of endpoints) {
    for (const f of ep.fields) {
      if (f.type === 'enum') continue; // enum uses <select>, no typedInput needed

      const key     = fieldPropKey(ep.operationId, f.name);
      const keyType = fieldTypePropKey(ep.operationId, f.name);
      const types   = typedInputTypes(f.type);

      if (f.type === 'array-of-string') {
        // Read saved JSON BEFORE typedInput init: typedInput with hasValue:false clears the input value on init
        lines.push(`${ind}var _${key}_rawJson = $('#node-input-${key}').val() || '[]';`);
      }

      lines.push(`${ind}$('#node-input-${key}').typedInput({`);
      lines.push(`${ind}  typeField: '#node-input-${keyType}',`);
      lines.push(`${ind}  types: ${types},`);
      lines.push(`${ind}});`);

      if (f.type === 'array-of-string') {
        lines.push(`${ind}// editableList for '${f.name}'`);
        lines.push(`${ind}$('#${key}-list').editableList({`);
        lines.push(`${ind}  height: 'auto',`);
        lines.push(`${ind}  addItem: function(container, i, opt) {`);
        lines.push(`${ind}    var val = typeof opt === 'string' ? opt : '';`);
        lines.push(`${ind}    var inp = $('<input/>', { type: 'text', style: 'width:100%', 'class': 'aoi-val' });`);
        lines.push(`${ind}    inp.val(val);`);
        lines.push(`${ind}    container.append(inp);`);
        lines.push(`${ind}  },`);
        lines.push(`${ind}  removable:  true,`);
        lines.push(`${ind}  sortable:   true,`);
        lines.push(`${ind}  addButton:  false,`);
        lines.push(`${ind}});`);
        lines.push(`${ind}try {`);
        lines.push(`${ind}  var _${key}_saved = JSON.parse(_${key}_rawJson);`);
        lines.push(`${ind}  var _${key}_items = Array.isArray(_${key}_saved) ? _${key}_saved : [];`);
        lines.push(`${ind}  if (_${key}_items.length === 0) _${key}_items = [''];`);
        lines.push(`${ind}  _${key}_items.forEach(function(item) { $('#${key}-list').editableList('addItem', item); });`);
        lines.push(`${ind}} catch(e) { $('#${key}-list').editableList('addItem', ''); }`);
        lines.push(`${ind}$('#${key}-list-add').on('click', function(e) { e.preventDefault(); $('#${key}-list').editableList('addItem', ''); });`);
        lines.push(`${ind}function _${key}_refreshList() {`);
        lines.push(`${ind}  var t = $('#node-input-${keyType}').val() || 'list';`);
        lines.push(`${ind}  var fieldVisible = $('#node-input-${key}').closest('.ep-field-row').is(':visible');`);
        lines.push(`${ind}  if (t === 'list' && fieldVisible) { $('.array-list-row[data-for="${key}"]').show(); }`);
        lines.push(`${ind}  else                              { $('.array-list-row[data-for="${key}"]').hide(); }`);
        lines.push(`${ind}}`);
        lines.push(`${ind}$('#node-input-${key}').on('change', function() { _${key}_refreshList(); });`);
        lines.push(`${ind}_${key}_refreshList();`);
      }
    }
  }

  return lines.join('\n');
}

function typedInputTypes(fieldType: string): string {
  switch (fieldType) {
    case 'number':          return "['num', 'msg', 'flow', 'global', 'env']";
    case 'boolean':         return "['bool', 'msg', 'flow', 'global', 'env']";
    case 'array-of-string': return "[{ value: 'list', label: 'list', icon: 'fa fa-list', hasValue: false }, 'msg', 'flow']";
    case 'binary':
      return "[{ value: 'str', label: 'file path', icon: 'fa fa-file' }, 'msg', 'flow', 'global', 'env']";
    default:
      return "['str', 'msg', 'flow', 'global', 'env']";
  }
}
