import type { NodeDef, EndpointDef, FieldDef, SecurityDef } from './types';
import { toPascalCase, fieldPropKey, fieldTypePropKey, defaultTypeStr } from './utils';

/**
 * Generates node.js for a Node-RED custom node (the runtime CommonJS module).
 *
 * The generated file exports `module.exports = function(RED) { ... }` that registers
 * two Node-RED types:
 *   - Auth config node (`${nodeName}-auth-config`): stores the API key credential.
 *   - Main node (`${nodeName}`): on each incoming message, resolves field values,
 *     applies auth, and dispatches the HTTP request via axios.
 *
 * Field value resolution mirrors the TypedInput modes stored by the editor:
 *   - 'list' / 'map' mode  → genResolveTypedInput() deserializes stored JSON.
 *   - other modes          → RED.util.evaluateNodeProperty() resolves directly.
 */

/**
 * Entry point: generate whole contents for node-RED node.js
 *
 * @param nodeDef  Parsed node definition from the OpenAPI spec.
 * @param nodeName Node name used as the registered type name.
 * @returns Complete .js file content as a string (CommonJS module).
 */
export function generateRuntime(nodeDef: NodeDef, nodeName: string): string {
  const Pascal = toPascalCase(nodeName);
  return [
    `// Auto-generated by node-red-nodegen-openapi. Do not edit manually.`,
    `'use strict';`,
    ``,
    `const axios    = require('axios');`,
    `const FormData = require('form-data');`,
    `const fs       = require('fs');`,
    `const https    = require('https');`,
    ``,
    `module.exports = function(RED) {`,
    ``,
    genAuthConfigNode(nodeName, Pascal, nodeDef.security),
    ``,
    genMainNode(nodeName, Pascal, nodeDef),
    ``,
    `};`,
  ].join('\n');
}

/**
 * Generates the auth config node — a dedicated config node that keeps API credentials
 * separate from the main node, enabling sharing across instances and Node-RED's
 * encrypted credential storage.
 *
 * The auth config node only stores credentials and has no `input` handler.
 * Credentials are declared as `{ apiKey: { type: 'password' } }` so Node-RED
 * encrypts them in storage.
 *
 * @param nodeName Node name (used to build the config node type `${nodeName}-auth-config`).
 * @param Pascal   PascalCase version of nodeName for the constructor function name.
 * @param security Security scheme definitions (not used in the generated code; reserved for future use).
 * @returns JS string for the auth config node constructor and registerType call.
 */
function genAuthConfigNode(nodeName: string, Pascal: string, security: SecurityDef[]): string {
  const lines: string[] = [];
  lines.push(`  // ----- Auth Config Node -----`);
  lines.push(`  function ${Pascal}AuthConfigNode(config) {`);
  lines.push(`    RED.nodes.createNode(this, config);`);
  lines.push(`  }`);
  lines.push(`  RED.nodes.registerType('${nodeName}-auth-config', ${Pascal}AuthConfigNode, {`);
  lines.push(`    credentials: { apiKey: { type: 'password' } },`);
  lines.push(`  });`);
  return lines.join('\n');
}

/**
 * Generates the main API-caller node: receives incoming Node-RED messages, reads
 * the user-configured endpoint and field values from config, executes the API call,
 * and forwards the response to the next node.
 *
 * On each incoming message the handler executes in this order:
 *   1. Reads `config.endpoint` (operationId) and resolves the linked auth config node.
 *   2. Applies the API key to headers or query params via genAuthBlock.
 *   3. Sets `method`, `url`, `requestData`, `params`, and `headers` via genEndpointSwitch.
 *   4. Executes the HTTP request and forwards the response via genAxiosCall.
 *
 * @param nodeName Node name used as the registered type name.
 * @param Pascal   PascalCase version of nodeName for the constructor function name.
 * @param nodeDef  Parsed node definition supplying security, server URL, and endpoints.
 * @returns JS string for the main node constructor and registerType call.
 */
function genMainNode(nodeName: string, Pascal: string, nodeDef: NodeDef): string {
  const lines: string[] = [];
  lines.push(`  // ----- Main Node -----`);
  lines.push(`  function ${Pascal}Node(config) {`);
  lines.push(`    RED.nodes.createNode(this, config);`);
  lines.push(`    const node = this;`);
  lines.push(``);
  lines.push(`    node.on('input', function(msg, send, done) {`);
  lines.push(`      const authNode = RED.nodes.getNode(config.authConfig);`);
  lines.push(`      const endpoint = config.endpoint;`);
  lines.push(`      const baseUrl  = '${nodeDef.serverUrl}';`);
  lines.push(``);  // `let` (not `const`): these three are assigned inside the endpoint switch branches.  lines.push(`      let method, url, requestData;`);
  lines.push(`      const params  = {};`);
  lines.push(`      const headers = {};`);
  lines.push(``);
  lines.push(genAuthBlock(nodeDef.security));
  lines.push(``);
  lines.push(genEndpointSwitch(nodeDef.endpoints));
  lines.push(``);
  lines.push(genAxiosCall());
  lines.push(`    });`);
  lines.push(`  }`);
  lines.push(``);
  lines.push(`  RED.nodes.registerType('${nodeName}', ${Pascal}Node);`);
  return lines.join('\n');
}

/**
 * Generates the API key injection block that applies the credential from the linked
 * auth config node to the outgoing request (header or query param, depending on the
 * security scheme).
 *
 * If no security schemes are defined, emits a no-op comment.
 * When both header and query schemes coexist, the generated code branches at runtime on
 * `authNode.scheme` — this mirrors the scheme `<select>` in the editor UI that is rendered
 * by genAuthConfigHtml when `security.length > 1`.
 *
 * @param security Security scheme definitions from the OpenAPI spec.
 * @returns JS string for the API key injection block.
 */
function genAuthBlock(security: SecurityDef[]): string {
  if (security.length === 0) return `      // No security schemes defined.`;

  const headerSchemes = security.filter(s => s.in === 'header');
  const querySchemes  = security.filter(s => s.in === 'query');

  const lines: string[] = [];
  lines.push(`      // Apply authentication`);
  lines.push(`      if (authNode && authNode.credentials && authNode.credentials.apiKey) {`);
  lines.push(`        const apiKey = authNode.credentials.apiKey;`);

  // If query schemes exist, emit a runtime branch on authNode.scheme; otherwise a direct header assignment.
  if (querySchemes.length > 0) {
    lines.push(`        if (authNode.scheme === '${querySchemes[0].name}') {`);
    lines.push(`          params['${querySchemes[0].keyName}'] = apiKey;`);
    if (headerSchemes.length > 0) {
      lines.push(`        } else {`);
      lines.push(`          headers['${headerSchemes[0].keyName}'] = apiKey;`);
    }
    lines.push(`        }`);
  } else if (headerSchemes.length > 0) {
    lines.push(`        headers['${headerSchemes[0].keyName}'] = apiKey;`);
  }

  lines.push(`      }`);
  return lines.join('\n');
}

/**
 * Generates the endpoint parameter extraction block covering all defined APIs: for
 * each endpoint, reads field values from the editor config and assembles
 * method/url/requestData/params/headers ready for the axios call.
 * Delegates per-endpoint extraction to genEndpointBlock.
 *
 * An unrecognized endpoint (not in the OpenAPI spec) calls `done(new Error(...))` and returns early.
 *
 * @param endpoints List of endpoint definitions from the parsed OpenAPI spec.
 * @returns JS string for the full endpoint dispatch block.
 */
function genEndpointSwitch(endpoints: EndpointDef[]): string {
  const lines: string[] = [];
  endpoints.forEach((ep, i) => {
    const kw = i === 0 ? 'if' : '} else if';
    lines.push(`      ${kw} (endpoint === '${ep.operationId}') {`);
    lines.push(genEndpointBlock(ep));
  });
  lines.push(`      } else {`);
  lines.push(`        done(new Error('Unknown endpoint: ' + endpoint));`);
  lines.push(`        return;`);
  lines.push(`      }`);
  return lines.join('\n');
}

/**
 * Generates one endpoint's parameter extraction block, used as a helper by genEndpointSwitch.
 * Reads each field value from the editor config, resolves it via typedInput evaluation,
 * and assigns it to the appropriate request target (path, header, query param, or body).
 *
 * Fields are resolved by their `location` property in this order:
 *   1. path   — substituted into the URL template via `encodeURIComponent`.
 *   2. header — added to `headers` if the resolved value is non-empty.
 *   3. query  — added to `params`; array-of-string uses genResolveTypedInput ('list' mode).
 *   4. body   — routed to genMultipartBody, genRawBody, or genJsonBody based on
 *               `ep.contentType` and the field types present.
 *
 * cf. `genResolveTypedInput()` — handles list/map deserialization for array-of-string
 *     and additionalProperties fields.
 *
 * @param ep Endpoint definition containing method, path, fields, and contentType.
 * @returns JS string for the endpoint branch body (no enclosing braces).
 */
function genEndpointBlock(ep: EndpointDef): string {
  const lines: string[] = [];
  const ind = '        '; // 8 spaces

  lines.push(`${ind}method = '${ep.method}';`);

  // Build URL (substitute path parameters)
  lines.push(`${ind}url = baseUrl + '${ep.path}';`);
  const pathFields = ep.fields.filter(f => f.location === 'path');
  for (const f of pathFields) {
    const key = fieldPropKey(ep.operationId, f.name);
    const keyType = fieldTypePropKey(ep.operationId, f.name);
    lines.push(`${ind}const _${key} = RED.util.evaluateNodeProperty(config['${key}'], config['${keyType}'] || 'str', node, msg);`);
    lines.push(`${ind}url = url.replace('{${f.name}}', encodeURIComponent(String(_${key})));`);
  }

  // Header parameters
  const headerFields = ep.fields.filter(f => f.location === 'header');
  for (const f of headerFields) {
    const key = fieldPropKey(ep.operationId, f.name);
    const keyType = fieldTypePropKey(ep.operationId, f.name);
    lines.push(`${ind}const _${key} = RED.util.evaluateNodeProperty(config['${key}'], config['${keyType}'] || 'str', node, msg);`);
    lines.push(`${ind}if (_${key} !== undefined && _${key} !== null && String(_${key}) !== '') headers['${f.name}'] = String(_${key});`);
  }

  // Query parameters
  const queryFields = ep.fields.filter(f => f.location === 'query');
  for (const f of queryFields) {
    const key = fieldPropKey(ep.operationId, f.name);
    const keyType = fieldTypePropKey(ep.operationId, f.name);
    if (f.type === 'array-of-string') {
      lines.push(...genResolveTypedInput(key, keyType, key, ind, 'list'));
      lines.push(`${ind}if (_${key} !== undefined && _${key} !== null) params['${f.name}'] = _${key};`);
    } else {
      lines.push(`${ind}const _${key} = RED.util.evaluateNodeProperty(config['${key}'], config['${keyType}'] || 'str', node, msg);`);
      lines.push(`${ind}if (_${key} !== undefined && _${key} !== null) params['${f.name}'] = _${key};`);
    }
  }

  // Body
  const bodyFields = ep.fields.filter(f => f.location === 'body');
  if (bodyFields.length > 0) {
    /**
     *  TODO: Refactor in the future. The logic below works for now but is ad-hoc.
     *   - Most cases can be handled by genJsonBody.
     *   - Other cases need to cover:
     *     - multipart/form-data
     *     - requestBody with a single binary field
     */
    if (ep.contentType === 'multipart/form-data') {
      lines.push(...genMultipartBody(ep.operationId, bodyFields, ind));
    } else if (bodyFields.length === 1 && bodyFields[0].type === 'binary') {
      lines.push(...genRawBody(ep.operationId, bodyFields[0], ind));
    } else {
      lines.push(...genJsonBody(ep.operationId, bodyFields, ind));
    }
  }

  return lines.join('\n');
}

/**
 * Generates the TypedInput evaluation snippet that resolves a single field's stored
 * value into a JS variable, handling all modes (list/map/direct). Because the editor
 * serializes values differently per mode (list → JSON array of {t,v}; map → JSON object
 * of {t,v}; others → value stored directly), all extractors (query params, body builders)
 * delegate here instead of duplicating mode-dispatch logic.
 *
 * `defaultMode` is the fallback when `config[keyType]` is absent (nodes saved before this
 * field type was introduced; version-up migration). Pass 'list' for array-of-string fields,
 * 'map' for additionalProperties fields.
 *
 * cf. `genWidgetInits()` in generate-html.ts — serializes values into the same `{t, v}` structures
 *     that this function reads back at runtime.
 *
 * @param key         Property key in `config` holding the serialized value string.
 * @param keyType     Property key in `config` holding the TypedInput mode string.
 * @param varSuffix   Suffix for the generated `_${varSuffix}` local variable name.
 * @param ind         Indentation string (spaces) to prepend to each generated line.
 * @param defaultMode Fallback TypedInput mode when `config[keyType]` is absent.
 * @returns Array of JS statement strings (without trailing newline).
 */
function genResolveTypedInput(key: string, keyType: string, varSuffix: string, ind: string, defaultMode: 'list' | 'map'): string[] {
  return [
    `${ind}const _${varSuffix}_t = config['${keyType}'] || '${defaultMode}';`,
    `${ind}let _${varSuffix};`,
    `${ind}if (_${varSuffix}_t === 'list') {`,
    `${ind}  try {`,
    `${ind}    const _${varSuffix}_raw = JSON.parse(config['${key}'] || '[]');`,
    `${ind}    _${varSuffix} = Array.isArray(_${varSuffix}_raw) ? _${varSuffix}_raw.map(function(item) {`,
    `${ind}      return (item && typeof item === 'object' && !Array.isArray(item))`,
    `${ind}        ? RED.util.evaluateNodeProperty(item.v, item.t || 'str', node, msg)`,
    `${ind}        : item;`,
    `${ind}    }) : [];`,
    `${ind}  } catch(e) { _${varSuffix} = []; }`,
    `${ind}} else if (_${varSuffix}_t === 'map') {`,
    `${ind}  try {`,
    `${ind}    const _${varSuffix}_raw = JSON.parse(config['${key}'] || '{}');`,
    `${ind}    _${varSuffix} = {};`,
    `${ind}    Object.keys(_${varSuffix}_raw).forEach(function(k) {`,
    `${ind}      var entry = _${varSuffix}_raw[k];`,
    `${ind}      if (Array.isArray(entry)) {`,
    `${ind}        _${varSuffix}[k] = entry.map(function(item) {`,
    `${ind}          return (item && typeof item === 'object' && !Array.isArray(item))`,
    `${ind}            ? RED.util.evaluateNodeProperty(item.v, item.t || 'str', node, msg)`,
    `${ind}            : item;`,
    `${ind}        });`,
    `${ind}      } else if (entry && typeof entry === 'object') {`,
    `${ind}        _${varSuffix}[k] = RED.util.evaluateNodeProperty(entry.v, entry.t || 'str', node, msg);`,
    `${ind}      } else {`,
    `${ind}        _${varSuffix}[k] = entry;`,
    `${ind}      }`,
    `${ind}    });`,
    `${ind}  } catch(e) { _${varSuffix} = {}; }`,
    `${ind}} else {`,
    `${ind}  _${varSuffix} = RED.util.evaluateNodeProperty(config['${key}'], _${varSuffix}_t, node, msg);`,
    `${ind}}`,
  ];
}

/**
 * Generates the `application/json` request body builder that assembles and resolves
 * all body fields from the editor config.
 *
 * Each field is resolved by type:
 *   - enum                 → read directly from `config` (plain `<select>` value, no TypedInput).
 *   - additionalProperties → genResolveTypedInput in 'map' mode; spread into body via Object.assign.
 *   - array-of-string      → genResolveTypedInput in 'list' mode; assigned as a JS array.
 *   - others               → RED.util.evaluateNodeProperty with the field's default TypedInput mode.
 *
 * Sets `requestData` to the built object and appends `Content-Type: application/json`.
 *
 * @param operationId Operation ID of the endpoint, used for fieldPropKey/fieldTypePropKey lookups.
 * @param fields      Body fields for this endpoint.
 * @param ind         Indentation string for the generated lines.
 * @returns Array of JS statement strings.
 */
function genJsonBody(operationId: string, fields: FieldDef[], ind: string): string[] {
  const lines: string[] = [];
  lines.push(`${ind}const _body = {};`);
  for (const f of fields) {
    const key = fieldPropKey(operationId, f.name);
    if (f.type === 'enum') {
      lines.push(`${ind}_body['${f.name}'] = config['${key}'];`);
    } else if (f.isAdditionalProperties) {
      const keyType = fieldTypePropKey(operationId, f.name);
      lines.push(...genResolveTypedInput(key, keyType, key, ind, 'map'));
      lines.push(`${ind}Object.assign(_body, _${key});`);
    } else if (f.type === 'array-of-string') {
      const keyType = fieldTypePropKey(operationId, f.name);
      lines.push(...genResolveTypedInput(key, keyType, key, ind, 'list'));
      lines.push(`${ind}_body['${f.name}'] = _${key};`);
    } else {
      const keyType = fieldTypePropKey(operationId, f.name);
      const defType = defaultTypeStr(f.type);
      lines.push(`${ind}_body['${f.name}'] = RED.util.evaluateNodeProperty(config['${key}'], config['${keyType}'] || '${defType}', node, msg);`);
    }
  }
  lines.push(`${ind}requestData = _body;`);
  lines.push(`${ind}headers['Content-Type'] = 'application/json';`);
  return lines;
}

/**
 * Generates the raw body builder that passes a single binary or plain-string field
 * directly as the request body, for endpoints whose entire body is one field.
 *
 * For binary fields: if the resolved value is a string it is treated as a file path and wrapped
 * in `fs.createReadStream()`; a Buffer or stream is passed through directly.
 * For other types: the resolved value is assigned to `requestData` as-is.
 *
 * `requestData` is set only when the resolved value is non-empty.
 *
 * @param operationId Operation ID of the endpoint, used for fieldPropKey/fieldTypePropKey lookups.
 * @param field       The single body field definition.
 * @param ind         Indentation string for the generated lines.
 * @returns Array of JS statement strings.
 */
function genRawBody(operationId: string, field: FieldDef, ind: string): string[] {
  const key = fieldPropKey(operationId, field.name);
  const keyType = fieldTypePropKey(operationId, field.name);
  const lines: string[] = [];
  lines.push(`${ind}const _${key} = RED.util.evaluateNodeProperty(config['${key}'], config['${keyType}'] || 'str', node, msg);`);
  lines.push(`${ind}if (_${key} !== undefined && _${key} !== null && _${key} !== '') {`);
  if (field.type === 'binary') {
    lines.push(`${ind}  requestData = typeof _${key} === 'string' ? fs.createReadStream(_${key}) : _${key};`);
  } else {
    lines.push(`${ind}  requestData = _${key};`);
  }
  lines.push(`${ind}}`);
  return lines;
}

/**
 * Generates the `multipart/form-data` body builder that appends each field to a
 * FormData object, with type-specific handling per field.
 *
 * Field appending strategy by type:
 *   - enum                 → append raw config value if non-empty.
 *   - binary               → three sub-cases (in order of precedence):
 *                              1. string → treated as file path; `fs.createReadStream()`.
 *                              2. `{ value: Buffer, options }` → node-red http-request compatible format.
 *                              3. bare Buffer → appended with filename from `msg.filename` or 'upload.bin'.
 *   - additionalProperties → genResolveTypedInput in 'map' mode; each key appended individually
 *                             (array values expanded as repeated fields).
 *   - array-of-string      → genResolveTypedInput in 'list' mode; each item appended as a repeated field.
 *   - others               → evaluateNodeProperty; append as string if non-empty.
 *
 * Sets `requestData = _fd` and merges FormData headers into `headers` via `_fd.getHeaders()`.
 *
 * @param operationId Operation ID of the endpoint, used for fieldPropKey/fieldTypePropKey lookups.
 * @param fields      Body fields for this endpoint.
 * @param ind         Indentation string for the generated lines.
 * @returns Array of JS statement strings.
 */
function genMultipartBody(operationId: string, fields: FieldDef[], ind: string): string[] {
  const lines: string[] = [];
  lines.push(`${ind}const _fd = new FormData();`);
  for (const f of fields) {
    const key = fieldPropKey(operationId, f.name);
    if (f.type === 'enum') {
      lines.push(`${ind}if (config['${key}']) _fd.append('${f.name}', config['${key}']);`);
    } else if (f.type === 'binary') {
      const keyType = fieldTypePropKey(operationId, f.name);
      lines.push(`${ind}const _${key} = RED.util.evaluateNodeProperty(config['${key}'], config['${keyType}'] || 'str', node, msg);`);
      lines.push(`${ind}if (_${key} !== undefined && _${key} !== null && _${key} !== '') {`);
      lines.push(`${ind}  if (typeof _${key} === 'string') {`);
      lines.push(`${ind}    const _${key}_basename = require('path').basename(_${key});`);
      lines.push(`${ind}    _fd.append('${f.name}', fs.createReadStream(_${key}), { filename: _${key}_basename });`);
      lines.push(`${ind}  } else if (_${key} && typeof _${key} === 'object' && 'value' in _${key}) {`);
      lines.push(`${ind}    // node-red standard http request compatibility: { value: Buffer, options: { filename, contentType } }`);
      lines.push(`${ind}    _fd.append('${f.name}', _${key}.value, _${key}.options || {});`);
      lines.push(`${ind}  } else if (Buffer.isBuffer(_${key})) {`);
      lines.push(`${ind}    // keep simplest flow: direct connection from read file node as msg.payload`);
      lines.push(`${ind}    const _${key}_fname = msg.filename ? require('path').basename(msg.filename) : 'upload.bin';`);
      lines.push(`${ind}    _fd.append('${f.name}', _${key}, { filename: _${key}_fname });`);
      lines.push(`${ind}  } else {`);
      lines.push(`${ind}    _fd.append('${f.name}', _${key}, { filename: 'upload', contentType: 'application/octet-stream' });`);
      lines.push(`${ind}  }`);
      lines.push(`${ind}}`);
    } else if (f.isAdditionalProperties) {
      const keyType = fieldTypePropKey(operationId, f.name);
      lines.push(...genResolveTypedInput(key, keyType, key, ind, 'map'));
      lines.push(`${ind}Object.keys(_${key} || {}).forEach(function(k) {`);
      lines.push(`${ind}  var _apv = _${key}[k];`);
      lines.push(`${ind}  if (Array.isArray(_apv)) { _apv.forEach(function(item) { _fd.append(k, String(item)); }); }`);
      lines.push(`${ind}  else if (_apv !== undefined && _apv !== null && String(_apv) !== '') { _fd.append(k, String(_apv)); }`);
      lines.push(`${ind}});`);
    } else if (f.type === 'array-of-string') {
      const keyType = fieldTypePropKey(operationId, f.name);
      lines.push(...genResolveTypedInput(key, keyType, key, ind, 'list'));
      lines.push(`${ind}if (Array.isArray(_${key})) { _${key}.forEach(function(item) { _fd.append('${f.name}', String(item)); }); }`);
    } else {
      const keyType = fieldTypePropKey(operationId, f.name);
      const defType = defaultTypeStr(f.type);
      lines.push(`${ind}const _${key} = RED.util.evaluateNodeProperty(config['${key}'], config['${keyType}'] || '${defType}', node, msg);`);
      lines.push(`${ind}if (_${key} !== undefined && _${key} !== null && String(_${key}) !== '') _fd.append('${f.name}', String(_${key}));`);
    }
  }
  lines.push(`${ind}requestData = _fd;`);
  lines.push(`${ind}Object.assign(headers, _fd.getHeaders());`);
  return lines;
}

/**
 * Generates the axios call block that executes the HTTP request and routes the
 * response or error back into the Node-RED flow via `send()`/`done()`.
 *
 * Config resolution order:
 *   - Redirects: `config.followRedirects` / `config.maxRedirects` → `axios.maxRedirects`
 *                (0 disables redirect following).
 *   - TLS:       linked `tls-config` node via `config.tlsConfig`;
 *                `_tlsNode.addTLSOptions()` populates `httpsAgent`.
 *   - Proxy:     linked `http proxy` config node URL first; falls back to
 *                `HTTPS_PROXY` / `HTTP_PROXY` environment variables.
 *
 * Response handling:
 *   - Success:             sets `msg.payload`, `msg.statusCode`, `msg.responseHeaders`; calls send() + done().
 *   - HTTP error (with response): forwards error response body the same way (not thrown as error).
 *   - Network/other error: calls done(err) to surface as a Node-RED error.
 *
 * @returns JS string for the full axios call and response-handling block.
 */
function genAxiosCall(): string {
  return `
      // Build axios config
      const _axiosOpts = {
        method,
        url,
        headers,
        maxRedirects: config.followRedirects ? (parseInt(config.maxRedirects) || 5) : 0,
      };
      if (requestData !== undefined) _axiosOpts.data = requestData;
      if (Object.keys(params).length > 0) _axiosOpts.params = params;

      // TLS / SSL
      const _tlsNode = RED.nodes.getNode(config.tlsConfig);
      if (_tlsNode) {
        const _tlsOpts = {};
        _tlsNode.addTLSOptions(_tlsOpts);
        _axiosOpts.httpsAgent = new https.Agent(_tlsOpts);
      }

      // Proxy ('http proxy' config node, with env-var fallback)
      const _proxyNode = config.proxy ? RED.nodes.getNode(config.proxy) : null;
      const _proxyUrl  = (_proxyNode && _proxyNode.url)
                       || process.env.HTTPS_PROXY || process.env.HTTP_PROXY || '';
      if (_proxyUrl) {
        try {
          const _pu = new URL(_proxyUrl);
          _axiosOpts.proxy = {
            protocol: _pu.protocol.slice(0, -1),
            host:     _pu.hostname,
            port:     parseInt(_pu.port || (_pu.protocol === 'https:' ? '443' : '80')),
          };
          const _pUser = (_proxyNode && _proxyNode.credentials && _proxyNode.credentials.username) || _pu.username || '';
          const _pPass = (_proxyNode && _proxyNode.credentials && _proxyNode.credentials.password) || decodeURIComponent(_pu.password || '') || '';
          if (_pUser || _pPass) {
            _axiosOpts.proxy.auth = { username: _pUser, password: _pPass };
          }
        } catch (e) {
          node.warn('Invalid proxy URL: ' + _proxyUrl);
        }
      }

      axios(_axiosOpts)
        .then(function(res) {
          node.status({ fill: 'green', shape: 'dot', text: String(res.status) });
          msg.payload       = res.data;
          msg.statusCode    = res.status;
          msg.responseHeaders = res.headers;
          send(msg);
          done();
        })
        .catch(function(err) {
          node.status({ fill: 'red', shape: 'ring', text: err.message });
          if (err.response) {
            msg.payload       = err.response.data;
            msg.statusCode    = err.response.status;
            msg.responseHeaders = err.response.headers;
            send(msg);
            done();
          } else {
            done(err);
          }
        });`;
}
