import path from 'node:path';
import type { NodeDef, EndpointDef, FieldDef, SecurityDef, CliOptions } from './types';
import { fieldPropKey, fieldTypePropKey, defaultTypeStr } from './utils';

/**
 * Generates node.html for a Node-RED custom node.
 *
 * A node.html consists of two independently registered types:
 *   - Auth config node  (`${nodeName}-auth-config`): credentials holder, shared across instances.
 *   - Main node         (`${nodeName}`): the API caller node shown in the palette.
 *
 * The main node's editor UI relies on three cooperating functions that must stay in sync:
 *   - genDefaults()    — declares all field properties and their initial TypedInput modes
 *                        in the `defaults:` block of registerType.
 *   - genWidgetInits() — initializes typedInput / editableList widgets in oneditprepare,
 *                        restoring saved values using the modes set by genDefaults.
 *   - genRegistration()— wires endpoint show/hide, list/map toggles, and oneditsave
 *                        serialization back to hidden `<input>` elements.
 */

/**
 * Entry point: generate whole contents for node-RED node.html
 *
 * Node-RED requires two separately registered types per API node:
 *   1. Auth config node (`${nodeName}-auth-config`) — credentials node shared across
 *      multiple instances; stored independently so the API key is not duplicated per node.
 *   2. Main node (`${nodeName}`) — the actual API caller.
 * These are generated as distinct `<script>` blocks concatenated in one file.
 *
 * @param nodeDef  Parsed node definition from the OpenAPI spec.
 * @param nodeName Node name used as the registered type name.
 * @param opts     CLI options (icon, color, category, etc.).
 * @returns Complete .html file content.
 */
export function generateHtml(nodeDef: NodeDef, nodeName: string, opts: CliOptions): string {
  return [
    `<!-- Auto-generated by node-red-nodegen-openapi. Do not edit manually. -->`,
    ``,
    genAuthConfigHtml(nodeName, nodeDef.security),
    ``,
    genMainNodeHtml(nodeName, nodeDef, opts),
  ].join('\n');
}

/**
 * Generates the auth config part, including dialog, help text, and registerType
 *
 * The scheme `<select>` is rendered only when multiple security schemes are defined;
 * a single scheme requires no selection UI since there is nothing to choose from.
 *
 * @param nodeName Node name used as the registered type name prefix.
 * @param security Security scheme definitions parsed from the OpenAPI spec.
 * @returns HTML string with two `<script type="text/html">` blocks and one
 *          `<script type="text/javascript">` registration block.
 */
function genAuthConfigHtml(nodeName: string, security: SecurityDef[]): string {
  const configNodeType = `${nodeName}-auth-config`;
  const schemeOptions = security
    .map(s => `      <option value="${s.name}">${s.in === 'header' ? 'Header' : 'Query'}: ${s.keyName}</option>`)
    .join('\n');

  return [
    `<!-- ===== Auth Config Node ===== -->`,
    `<script type="text/html" data-template-name="${configNodeType}">`,
    `  <div class="form-row">`,
    `    <label for="node-config-input-name"><i class="fa fa-tag"></i> Name</label>`,
    `    <input type="text" id="node-config-input-name" placeholder="Name">`,
    `  </div>`,
    security.length > 1 ? [
      `  <div class="form-row">`,
      `    <label for="node-config-input-scheme"><i class="fa fa-key"></i> Scheme</label>`,
      `    <select id="node-config-input-scheme" style="width:70%">`,
      schemeOptions,
      `    </select>`,
      `  </div>`,
    ].join('\n') : '',
    `  <div class="form-row">`,
    `    <label for="node-config-input-apiKey"><i class="fa fa-lock"></i> API Key</label>`,
    `    <input type="password" id="node-config-input-apiKey" placeholder="API Key">`,
    `  </div>`,
    `</script>`,
    ``,
    `<script type="text/html" data-help-name="${configNodeType}">`,
    `  <p>Authentication configuration for the <b>${nodeName}</b> node.</p>`,
    `</script>`,
    ``,
    `<script type="text/javascript">`,
    `  RED.nodes.registerType('${configNodeType}', {`,
    `    category: 'config',`,
    `    defaults: {`,
    `      name:   { value: '' },`,
    security.length > 1 ? `      scheme: { value: '${security[0].name}' },` : '',
    `    },`,
    `    credentials: { apiKey: { type: 'password' } },`,
    `    label: function() { return this.name || '${nodeName} auth'; },`,
    `  });`,
    `</script>`,
  ].filter(l => l !== '').join('\n');
}

/**
 * Generates the main part, all excepts auth-config dialog.
 *
 * Accepts `opts` for icon, color, and category are CLI-level concerns
 * not present in the OpenAPI spec and therefore not stored in NodeDef.
 * Help blocks for binary and additionalProperties fields are auto-generated from
 * field metadata to reduce manual documentation burden on spec authors.
 *
 * @param nodeName Node name used as the registered type name.
 * @param nodeDef  Parsed node definition from the OpenAPI spec.
 * @param opts     CLI options supplying icon, color, and category.
 * @returns HTML string for the main node.
 */
function genMainNodeHtml(nodeName: string, nodeDef: NodeDef, opts: CliOptions): string {
  const color = opts.color ? `#${opts.color}` : '#87A980';
  const icon  = opts.icon  ? path.basename(opts.icon) : 'font-awesome/fa-cloud';

  // Collect all binary fields across all endpoints (deduplicate by field name)
  const binaryFields = [
    ...new Map(
      nodeDef.endpoints
        .flatMap(ep => ep.fields.filter(f => f.type === 'binary'))
        .map(f => [f.name, f])
    ).values()
  ];
  const binaryHelpBlocks = binaryFields.map(f => [
    `  <h3>${f.name}</h3>`,
    `  <p>To pass a file from a flow, set <b>${f.name}</b> to <code>msg.payload.${f.name}</code> in the UI, and send like below:</p>`,
    `  <pre>msg.payload = {\n  "${f.name}": {\n    "value": &lt;Buffer&gt;,        // file binary content (Buffer type)\n    "options": {\n      "filename": "yourfile.jpg"  // any filename with appropriate extension\n    }\n  }\n}</pre>`,
  ].join('\n')).join('\n');

  // Collect all additionalProperties fields across all endpoints (deduplicate by field name)
  const apFields = [
    ...new Map(
      nodeDef.endpoints
        .flatMap(ep => ep.fields.filter(f => f.isAdditionalProperties))
        .map(f => [f.name, f])
    ).values()
  ];
  const apHelpBlocks = apFields.length === 0 ? '' : [
    `  <h3>Additional Properties fields</h3>`,
    `  <p>Fields marked as <b>additionalProperties</b> (e.g. <b>${apFields.map(f => f.name).join(', ')}</b>) support two modes:</p>`,
    `  <dl>`,
    `    <dt><b>map</b> mode</dt>`,
    `    <dd>Define key-value pairs statically in the UI. Each value can be a literal string/number/boolean, or reference a <code>msg</code>, <code>flow</code>, <code>global</code>, or <code>env</code> property.<br>`,
    `    Use this when you know the keys at design time.<br>`,
    `    Example: add a row <code>propA</code> → <code>"hello"</code> to send a fixed value, or <code>propA</code> → <code>msg.payload.propA</code> to inject a value from the incoming message.</dd>`,
    `    <dt><b>msg / flow / global / env</b> mode</dt>`,
    `    <dd>Point to an object (e.g. <code>msg.payload.extra</code>). All key-value pairs in that object are spread as additional properties.<br>`,
    `    Use this when the set of keys is dynamic and determined by the upstream flow.<br>`,
    `    Note: mixing statically defined keys with a dynamic object in the same request is not supported.</dd>`,
    `  </dl>`,
  ].join('\n');

  return [
    `<!-- ===== Main Node ===== -->`,
    `<script type="text/html" data-template-name="${nodeName}">`,
    genTemplate(nodeName, nodeDef),
    `</script>`,
    ``,
    `<script type="text/html" data-help-name="${nodeName}">`,
    `  <p>${nodeDef.description ?? nodeDef.title}</p>`,
    `  <p>Select an endpoint from the dropdown, fill in the fields, and send a message to trigger the API call.</p>`,
    binaryHelpBlocks,
    apHelpBlocks,
    `  <h3>Output</h3>`,
    `  <dl class="message-properties">`,
    `    <dt>payload</dt><dd>Response body from the API.</dd>`,
    `    <dt>statusCode</dt><dd>HTTP status code.</dd>`,
    `    <dt>responseHeaders</dt><dd>Response headers.</dd>`,
    `  </dl>`,
    `</script>`,
    ``,
    `<script type="text/javascript">`,
    genRegistration(nodeName, nodeDef, color, icon, opts.category),
    `</script>`,
  ].join('\n');
}

/**
 * Generates the edit dialog for all API endpoints.
 *
 * All endpoint field rows are emitted unconditionally (hidden by default) rather than
 * being generated only for the active endpoint. This is required because Node-RED's
 * `defaults` system binds each property to a DOM element by id at registration time;
 * missing elements at `oneditprepare` time would break save/restore.
 *
 * Endpoint visibility toggling is handled by JS in genRegistration.
 *
 * @param nodeName Node name used to generate input element ids.
 * @param nodeDef  Parsed node definition supplying endpoints and field lists.
 * @returns HTML string for the edit dialog template (no enclosing `<script>` tag).
 */
function genTemplate(nodeName: string, nodeDef: NodeDef): string {
  const lines: string[] = [];

  // Node name
  lines.push(`  <div class="form-row">`);
  lines.push(`    <label for="node-input-name"><i class="fa fa-tag"></i> Name</label>`);
  lines.push(`    <input type="text" id="node-input-name" placeholder="Name">`);
  lines.push(`  </div>`);

  // Endpoint selector
  lines.push(`  <div class="form-row">`);
  lines.push(`    <label for="node-input-endpoint"><i class="fa fa-plug"></i> Endpoint</label>`);
  lines.push(`    <select id="node-input-endpoint" style="width:70%">`);
  for (const ep of nodeDef.endpoints) {
    lines.push(`      <option value="${ep.operationId}">${ep.method.toUpperCase()} ${ep.path}</option>`);
  }
  lines.push(`    </select>`);
  lines.push(`  </div>`);

  // Per-endpoint field rows
  for (const ep of nodeDef.endpoints) {
    lines.push(``);
    lines.push(`  <!-- Fields: ${ep.method.toUpperCase()} ${ep.path} -->`);
    for (const f of ep.fields) {
      lines.push(genFieldRow(ep.operationId, f));
    }
  }

  // Common settings separator
  lines.push(``);
  lines.push(`  <hr>`);

  // Auth config
  lines.push(`  <div class="form-row">`);
  lines.push(`    <label for="node-input-authConfig"><i class="fa fa-key"></i> Auth</label>`);
  lines.push(`    <input type="text" id="node-input-authConfig">`);
  lines.push(`  </div>`);

  // TLS config
  lines.push(`  <div class="form-row">`);
  lines.push(`    <label for="node-input-tlsConfig"><i class="fa fa-lock"></i> TLS</label>`);
  lines.push(`    <input type="text" id="node-input-tlsConfig">`);
  lines.push(`  </div>`);

  // Proxy
  lines.push(`  <div class="form-row">`);
  lines.push(`    <label for="node-input-proxy"><i class="fa fa-exchange"></i> Proxy</label>`);
  lines.push(`    <input type="text" id="node-input-proxy">`);
  lines.push(`  </div>`);

  // Follow redirects
  lines.push(`  <div class="form-row">`);
  lines.push(`    <label>&nbsp;</label>`);
  lines.push(`    <input type="checkbox" id="node-input-followRedirects" style="display:inline-block; width:auto; margin-right:5px">`);
  lines.push(`    <label for="node-input-followRedirects" style="width:auto">Follow redirects</label>`);
  lines.push(`    <span style="margin-left:10px">max:</span>`);
  lines.push(`    <input type="number" id="node-input-maxRedirects" min="0" max="20" style="width:60px; margin-left:5px">`);
  lines.push(`  </div>`);

  return lines.join('\n');
}

/**
 * Generates each editable field in nodeRED for API endpoint with `<div class="form-row">`
 *
 * For `array-of-string` and `isAdditionalProperties` fields, two sibling rows are
 * emitted: the typedInput row (shown when mode is not 'list'/'map') and an
 * editableList container row (shown when mode is 'list'/'map'). Both carry
 * `data-endpoint` and `data-for` attributes so that endpoint show/hide logic and
 * mode-toggle JS in genRegistration can operate without knowing field details.
 *
 * For non-enum fields, a hidden `<input type="hidden" id="node-input-${keyType}">` is
 * also emitted alongside the visible input. This hidden element stores the TypedInput
 * mode (e.g. 'str', 'msg', 'list') and acts as the bridge between the editor UI,
 * the `defaults:` system (via `typeField:` in genWidgetInits), and the runtime
 * (read back by `genResolveTypedInput()` in generate-runtime.ts).
 *
 * @param operationId Operation ID of the endpoint this field belongs to.
 * @param field       Field definition from the OpenAPI spec.
 * @returns HTML string for the row(s), potentially including an editableList container.
 */
function genFieldRow(operationId: string, field: FieldDef): string {
  const key     = fieldPropKey(operationId, field.name);
  const keyType = fieldTypePropKey(operationId, field.name);
  const label   = field.required
    ? `${field.name} <span style="color:red" title="required">*</span>`
    : field.name;
  const tip     = field.description ? ` title="${field.description.replace(/"/g, '&quot;')}"` : '';

  const lines: string[] = [];
  lines.push(`  <div class="form-row ep-field-row" data-endpoint="${operationId}" style="display:none"${tip}>`);
  lines.push(`    <label for="node-input-${key}">${label}</label>`);

  if (field.type === 'enum' && field.enumValues) {
    lines.push(`    <select id="node-input-${key}" style="width:70%">`);
    for (const v of field.enumValues) {
      lines.push(`      <option value="${v}">${v}</option>`);
    }
    lines.push(`    </select>`);
  } else {
    const placeholder = field.isAdditionalProperties
      ? '(map)'
      : (field.description ? field.description.slice(0, 60) : field.name);
    lines.push(`    <input type="text" id="node-input-${key}" placeholder="${placeholder}" style="width:68%">`);
    lines.push(`    <input type="hidden" id="node-input-${keyType}">`);
  }

  lines.push(`  </div>`);

  // For array-of-string: editableList container (shown only in list mode)
  if (field.type === 'array-of-string') {
    lines.push(`  <div class="form-row ep-field-row array-list-row" data-endpoint="${operationId}" data-for="${key}" style="display:none">`);
    lines.push(`    <label>&nbsp;</label>`);
    lines.push(`    <ol id="${key}-list" style="width:70%;"></ol>`);
    lines.push(`    <div style="margin-left:105px; margin-top:4px;">`);
    lines.push(`      <a href="#" id="${key}-list-add" style="font-size:0.85em"><i class="fa fa-plus"></i> Add item</a>`);
    lines.push(`    </div>`);
    lines.push(`  </div>`);
  }

  // For additionalProperties: editableList container with key+value rows
  if (field.isAdditionalProperties) {
    lines.push(`  <div class="form-row ep-field-row ap-list-row" data-endpoint="${operationId}" data-for="${key}" style="display:none">`);
    lines.push(`    <label>&nbsp;</label>`);
    lines.push(`    <div style="width: calc(100% - 116px)">`);
    lines.push(`      <ol id="${key}-ap-list"></ol>`);
    lines.push(`      <a href="#" id="${key}-ap-list-add" style="font-size:0.85em"><i class="fa fa-plus"></i> Add entry</a>`);
    lines.push(`    </div>`);
    lines.push(`  </div>`);
  }

  return lines.join('\n');
}

/**
 * Generates the `RED.nodes.registerType(...)` call with oneditprepare, oneditsave and input
 *
 * oneditprepare handles three concerns in order:
 *   1. Endpoint show/hide — all `.ep-field-row` elements are toggled on endpoint change.
 *   2. list/map toggle — `.array-list-row` / `.ap-list-row` visibility mirrors the
 *      selected typedInput mode of their associated field.
 *   3. Widget initialization — delegated to genWidgetInits for readability.
 *
 * oneditsave serializes editableList state back to hidden `<input>` elements as JSON,
 * because Node-RED's defaults system only reads `<input>` values at save time.
 *
 * @param nodeName Node name used as the registered type name.
 * @param nodeDef  Parsed node definition supplying endpoints, defaults, and label.
 * @param color    Resolved CSS color string (e.g. '#87A980'), with '#' already prepended.
 * @param icon     Resolved icon filename (basename only; Font Awesome refs also accepted).
 * @param category Node-RED palette category.
 * @returns JS string for the `RED.nodes.registerType(...)` call.
 */
function genRegistration(nodeName: string, nodeDef: NodeDef, color: string, icon: string, category: string): string {
  const defaults = genDefaults(nodeName, nodeDef);
  const typedInputInits = genWidgetInits(nodeDef.endpoints);

  return [
    `  RED.nodes.registerType('${nodeName}', {`,
    `    category:     '${category}',`,
    `    color:        '${color}',`,
    `    defaults: {`,
    defaults,
    `    },`,
    `    inputs:  1,`,
    `    outputs: 1,`,
    `    icon:    '${icon}',`,
    `    label:   function() { return this.name || '${nodeName}'; },`,
    `    oneditprepare: function() {`,
    `      // Show/hide field rows based on selected endpoint`,
    `      function _updateFields() {`,
    `        var ep = $('#node-input-endpoint').val();`,
    `        $('.ep-field-row').hide();`,
    `        $('.ep-field-row[data-endpoint="' + ep + '"]').show();`,
    `        // Re-apply list mode visibility for array-of-string fields`,
    `        $('.array-list-row').each(function() {`,
    `          var forKey = $(this).data('for');`,
    `          var t = $('#node-input-' + forKey + 'Type').val() || 'list';`,
    `          var fieldVisible = $('#node-input-' + forKey).closest('.ep-field-row').is(':visible');`,
    `          if (t === 'list' && fieldVisible) { $(this).show(); } else { $(this).hide(); }`,
    `        });`,
    `        // Re-apply map mode visibility for additionalProperties fields`,
    `        $('.ap-list-row').each(function() {`,
    `          var forKey = $(this).data('for');`,
    `          var t = $('#node-input-' + forKey + 'Type').val() || 'map';`,
    `          var fieldVisible = $('#node-input-' + forKey).closest('.ep-field-row').is(':visible');`,
    `          if (t === 'map' && fieldVisible) { $(this).show(); } else { $(this).hide(); }`,
    `        });`,
    `      }`,
    `      $('#node-input-endpoint').on('change', _updateFields);`,
    `      _updateFields();`,
    ``,
    `      // typedInput widgets`,
    typedInputInits,
    `    },`,
    `    oneditsave: function() {`,
    `      // Only two field types use an editableList widget in the editor UI and need manual serialization here:`,
    `      //   - array-of-string fields(.array-list-row): rendered as a list of addable/removable items.`,
    `      //   - additionalProperties fields(.ap-list-row): rendered as a list of key-value pair rows.`,
    `      // Regular typedInput fields (str/num/bool/msg/flow) sync their value back to the hidden <input> automatically.`,
    `      // editableList widgets do NOT — their items live only in the DOM, so we must read them and write JSON into the hidden input before Node-RED's defaults system reads it.`,
    `      $('.array-list-row').each(function() {`,
    `        var forKey = $(this).data('for');`,
    `        // In msg/flow mode typedInput already wrote its value to the hidden input; only list mode needs manual serialization.`,
    `        if ($('#node-input-' + forKey + 'Type').val() !== 'list') return;`,
    `        var items = [];`,
    `        $(this).find('ol').editableList('items').each(function() {`,
    `          var _vt = $(this).find('.aoi-val').typedInput('type');`,
    `          var _vv = $(this).find('.aoi-val').typedInput('value');`,
    `          if (_vv !== undefined && _vv !== null && String(_vv).trim() !== '') items.push({ t: _vt, v: _vv });`,
    `        });`,
    `        var _el = document.getElementById('node-input-' + forKey);`,
    `        if (_el) _el.value = JSON.stringify(items);`,
    `      });`,
    `      $('.ap-list-row').each(function() {`,
    `        var forKey = $(this).data('for');`,
    `        // In msg/flow mode typedInput already wrote its value to the hidden input; only map mode needs manual serialization.`,
    `        if ($('#node-input-' + forKey + 'Type').val() !== 'map') return;`,
    `        var obj = {};`,
    `        $(this).find('ol[id]').editableList('items').each(function() {`,
    `          var k = String($(this).find('.ap-key').val() || '').trim();`,
    `          var subList = $(this).find('.ap-val-list');`,
    `          var v;`,
    `          if (subList.length > 0) {`,
    `            var arr = [];`,
    `            subList.editableList('items').each(function() {`,
    `              var _svt = $(this).find('.aoi-val').typedInput('type');`,
    `              var _svv = $(this).find('.aoi-val').typedInput('value');`,
    `              if (_svv !== undefined && _svv !== null && String(_svv).trim() !== '') arr.push({ t: _svt, v: _svv });`,
    `            });`,
    `            v = arr;`,
    `          } else {`,
    `            var _valT = $(this).find('.ap-val').typedInput('type');`,
    `            var _valV = $(this).find('.ap-val').typedInput('value');`,
    `            v = { t: _valT, v: _valV };`,
    `          }`,
    `          if (k !== '') obj[k] = v;`,
    `        });`,
    `        var _el = document.getElementById('node-input-' + forKey);`,
    `        if (_el) _el.value = JSON.stringify(obj);`,
    `      });`,
    `    }`,
    `  });`,
  ].join('\n');
}

/**
 * Generates the `defaults:` entries for RED.nodes.registerType.
 *
 * Each non-enum field emits two entries: the value key and a typeKey (suffixed 'Type')
 * that stores the TypedInput mode. This pairing is required so the runtime can
 * determine how to evaluate the stored value via evaluateNodeProperty.
 * Special initial values:
 *   - array-of-string      → value '[]',  type 'list'
 *   - additionalProperties → value '{}',  type 'map'
 *   - enum                 → value only (no typeKey; enum uses `<select>`, not typedInput)
 *
 * cf. `genWidgetInits()` — must stay consistent: the initial type value set here
 *     (e.g. 'list', 'map') is read back by genWidgetInits to restore saved state.
 *     Adding a new field type requires updating both functions in sync.
 *
 * @param nodeName Node name used to generate input element ids.
 * @param nodeDef  Parsed node definition supplying endpoints and field lists.
 * @returns Multi-line string of defaults entries, ready to splice into the registerType block.
 */
function genDefaults(nodeName: string, nodeDef: NodeDef): string {
  const lines: string[] = [];
  const ind = '      ';

  // Common node properties (shared across all endpoints).
  lines.push(`${ind}name:           { value: '' },`);
  lines.push(`${ind}endpoint:       { value: '${nodeDef.endpoints[0]?.operationId ?? ''}' },`);
  lines.push(`${ind}authConfig:     { value: '', type: '${nodeName}-auth-config', required: false },`);
  lines.push(`${ind}tlsConfig:      { value: '', type: 'tls-config', required: false },`);
  lines.push(`${ind}followRedirects:{ value: true },`);
  lines.push(`${ind}maxRedirects:   { value: 5 },`);
  lines.push(`${ind}proxy:          { value: '', type: 'http proxy', required: false },`);

  // Per-field entries: each field gets a value prop and (except enum) a type prop.
  for (const ep of nodeDef.endpoints) {
    for (const f of ep.fields) {
      const key     = fieldPropKey(ep.operationId, f.name);
      const keyType = fieldTypePropKey(ep.operationId, f.name);
      const defVal  = f.type === 'enum'
        ? (f.enumValues?.[0] ?? '')
        : (f.default !== undefined ? String(f.default) : '');

      if (f.type === 'enum') {
        lines.push(`${ind}${key}: { value: '${defVal}' },`);
      } else if (f.isAdditionalProperties) {
        lines.push(`${ind}${key}:     { value: '{}' },`);
        lines.push(`${ind}${keyType}: { value: 'map' },`);
      } else {
        const defType = defaultTypeStr(f.type);
        const defValue = f.type === 'array-of-string' ? '[]' : defVal;
        lines.push(`${ind}${key}:     { value: '${defValue}' },`);
        lines.push(`${ind}${keyType}: { value: '${defType}' },`); // 'str' | 'num' | 'bool' | 'list'
      }
    }
  }

  return lines.join('\n');
}

/**
 * Generates JS that initializes typedInput and editableList widgets inside oneditprepare.
 *
 * Initialization order within each field is critical:
 *   1. Capture the saved JSON string from the hidden `<input>` BEFORE typedInput init.
 *      typedInput with `hasValue: false` (list / map modes) clears the input value on
 *      init, so raw JSON must be read first.
 *   2. Init typedInput (wires typeField, renders the widget).
 *   3. Init editableList and restore saved items from the captured JSON.
 *
 * additionalProperties fields are handled in a dedicated block (with `continue`) to
 * avoid polluting the shared array-of-string path with deep conditionals.
 *
 * cf. `genDefaults()` — must stay consistent: the initial type value written there
 *     (e.g. 'list', 'map') is what this function reads back to restore saved state.
 *     Adding a new field type requires updating both functions in sync.
 * cf. `genResolveTypedInput()` in generate-runtime.ts — the runtime counterpart
 *     that reads and evaluates the same {t, v} structures stored here.
 *
 * @param endpoints List of endpoint definitions from the parsed OpenAPI spec.
 * @returns Multi-line JS string for use inside the `oneditprepare` callback.
 */
function genWidgetInits(endpoints: EndpointDef[]): string {
  const lines: string[] = [];
  const ind = '      ';

  for (const ep of endpoints) {
    for (const f of ep.fields) {
      if (f.type === 'enum') continue; // enum uses <select>, no typedInput needed

      const key     = fieldPropKey(ep.operationId, f.name);
      const keyType = fieldTypePropKey(ep.operationId, f.name);

      // additionalProperties field: handles (1)(2)(3) all in this block, then skips the standard path via continue.
      if (f.isAdditionalProperties) {
        // (1) Salvage saved value (must run before (2) typedInput init, which wipes input.value when hasValue:false)
        lines.push(`${ind}var _${key}_rawJson = $('#node-input-${key}').val() || '{}';`);
        // (2) typedInput init (outer map / msg / flow widget)
        lines.push(`${ind}$('#node-input-${key}').typedInput({`);
        lines.push(`${ind}  typeField: '#node-input-${keyType}',`);
        lines.push(`${ind}  types: ${typedInputTypes('additional-properties')},`);
        lines.push(`${ind}});`);
        // (3) editableList init and saved-value restore (key-value map rows UI)
        lines.push(`${ind}$('#${key}-ap-list').editableList({`);
        lines.push(`${ind}  height: 'auto',`);
        lines.push(`${ind}  removable: true,`);
        lines.push(`${ind}  sortable: true,`);
        lines.push(`${ind}  addButton: false,`);
        lines.push(`${ind}  addItem: function(container, i, opt) {`);
        if (f.type === 'array-of-string') {
          // Value is an array: render a mini editableList inside each AP row
          lines.push(`${ind}    var _k = (opt && opt.k !== undefined) ? String(opt.k) : '';`);
          lines.push(`${ind}    var _varr = (opt && Array.isArray(opt.v)) ? opt.v : [];`);
          lines.push(`${ind}    var row = $('<div>').css({ display: 'flex', gap: '4px', alignItems: 'flex-start', width: '100%' });`);
          lines.push(`${ind}    var keyInp = $('<input>', { type: 'text', placeholder: 'key', 'class': 'ap-key' }).css({ width: '35%', flex: 'none', marginTop: '6px' });`);
          lines.push(`${ind}    keyInp.val(_k);`);
          lines.push(`${ind}    var valWrap = $('<div>').css({ flex: '1', minWidth: '0' });`);
          lines.push(`${ind}    var valList = $('<ol>').addClass('ap-val-list');`);
          lines.push(`${ind}    var addLnk = $('<a>').attr('href','#').css({ fontSize:'0.8em', display:'block', marginTop:'2px' }).html('<i class="fa fa-plus"></i> add item');`);
          lines.push(`${ind}    valWrap.append(valList).append(addLnk);`);
          lines.push(`${ind}    row.append(keyInp).append(valWrap);`);
          lines.push(`${ind}    container.append(row);`);
          lines.push(`${ind}    valList.editableList({`);
          lines.push(`${ind}      height: 'auto',`);
          lines.push(`${ind}      removable: true,`);
          lines.push(`${ind}      sortable: true,`);
          lines.push(`${ind}      addButton: false,`);
          lines.push(`${ind}      addItem: function(c, i2, v) {`);
          lines.push(`${ind}        var _vObj = (v !== null && typeof v === 'object' && !Array.isArray(v)) ? v : null;`);
          lines.push(`${ind}        var _vt = _vObj ? String(_vObj.t || 'str') : 'str';`);
          lines.push(`${ind}        var _vv = _vObj ? String(_vObj.v !== undefined ? _vObj.v : '') : String(v || '');`);
          lines.push(`${ind}        var inp = $('<input>', { type: 'text', style: 'width:100%', 'class': 'aoi-val' });`);
          lines.push(`${ind}        c.append(inp);`);
          lines.push(`${ind}        inp.typedInput({ types: ${typedInputTypes('string')} });`);
          lines.push(`${ind}        inp.typedInput('type', _vt);`);
          lines.push(`${ind}        inp.typedInput('value', _vv);`);
          lines.push(`${ind}      },`);
          lines.push(`${ind}    });`);
          lines.push(`${ind}    (_varr.length > 0 ? _varr : [{ t: 'str', v: '' }]).forEach(function(v) { valList.editableList('addItem', v); });`);
          lines.push(`${ind}    addLnk.on('click', function(e) { e.preventDefault(); valList.editableList('addItem', { t: 'str', v: '' }); });`);
          lines.push(`${ind}  },`);
        } else {
          // Value is a scalar: use typedInput
          lines.push(`${ind}    var _k = (opt && opt.k !== undefined) ? String(opt.k) : '';`);
          lines.push(`${ind}    var _vObj = (opt && opt.v !== null && typeof opt.v === 'object' && !Array.isArray(opt.v)) ? opt.v : null;`);
          lines.push(`${ind}    var _vt = _vObj ? String(_vObj.t || 'str') : 'str';`);
          lines.push(`${ind}    var _vv = _vObj ? String(_vObj.v !== undefined ? _vObj.v : '') : '';`);
          lines.push(`${ind}    var row = $('<div>').css({ display: 'flex', gap: '4px', alignItems: 'center', width: '100%' });`);
          lines.push(`${ind}    var keyInp = $('<input>', { type: 'text', placeholder: 'key', 'class': 'ap-key' }).css({ width: '35%', flex: 'none' });`);
          lines.push(`${ind}    keyInp.val(_k);`);
          lines.push(`${ind}    var valInp = $('<input>', { type: 'text', 'class': 'ap-val' });`);
          lines.push(`${ind}    row.append(keyInp).append(valInp);`);
          lines.push(`${ind}    container.append(row);`);
          const valTypes = typedInputTypes(f.type);
          lines.push(`${ind}    valInp.typedInput({ types: ${valTypes} });`);
          lines.push(`${ind}    valInp.typedInput('type', _vt);`);
          lines.push(`${ind}    valInp.typedInput('value', _vv);`);
          lines.push(`${ind}    // In Node-RED v4, typedInput converts the input to type=hidden and adds a sibling div.red-ui-typedInput-container`);
          lines.push(`${ind}    valInp.next('.red-ui-typedInput-container').css({ flex: '1', minWidth: '0', width: '' });`);
          lines.push(`${ind}  },`);
        }
        lines.push(`${ind}});`);
        lines.push(`${ind}try {`);
        lines.push(`${ind}  var _${key}_saved = JSON.parse(_${key}_rawJson);`);
        lines.push(`${ind}  var _${key}_entries = (typeof _${key}_saved === 'object' && !Array.isArray(_${key}_saved) && _${key}_saved !== null)`);
        lines.push(`${ind}    ? Object.entries(_${key}_saved) : [];`);
        lines.push(`${ind}  if (_${key}_entries.length === 0) _${key}_entries = [['', '']];`);
        lines.push(`${ind}  _${key}_entries.forEach(function(e) { $('#${key}-ap-list').editableList('addItem', { k: e[0], v: e[1] }); });`);
        lines.push(`${ind}} catch(e) { $('#${key}-ap-list').editableList('addItem', { k: '', v: '' }); }`);
        lines.push(`${ind}$('#${key}-ap-list-add').on('click', function(e) { e.preventDefault(); $('#${key}-ap-list').editableList('addItem', { k: '', v: '' }); });`);
        lines.push(`${ind}function _${key}_refreshAp() {`);
        lines.push(`${ind}  var t = $('#node-input-${keyType}').val() || 'map';`);
        lines.push(`${ind}  var fieldVisible = $('#node-input-${key}').closest('.ep-field-row').is(':visible');`);
        lines.push(`${ind}  if (t === 'map' && fieldVisible) { $('.ap-list-row[data-for="${key}"]').show(); }`);
        lines.push(`${ind}  else                             { $('.ap-list-row[data-for="${key}"]').hide(); }`);
        lines.push(`${ind}}`);
        lines.push(`${ind}$('#node-input-${key}').on('change', function() { _${key}_refreshAp(); });`);
        lines.push(`${ind}_${key}_refreshAp();`);
        continue;
      }

      const types   = typedInputTypes(f.type);

      // (1) [array-of-string] Salvage saved value (must run before (2) typedInput init, which wipes input.value when hasValue:false)
      if (f.type === 'array-of-string') {
        lines.push(`${ind}var _${key}_rawJson = $('#node-input-${key}').val() || '[]';`);
      }

      // (2) typedInput init (common to all fields)
      lines.push(`${ind}$('#node-input-${key}').typedInput({`);
      lines.push(`${ind}  typeField: '#node-input-${keyType}',`);
      lines.push(`${ind}  types: ${types},`);
      lines.push(`${ind}});`);

      // (3) [array-of-string] editableList init and saved-value restore.
      //    Must run after (2) because addItem callbacks use typedInput internally.
      if (f.type === 'array-of-string') {
        lines.push(`${ind}// editableList for '${f.name}'`);
        lines.push(`${ind}$('#${key}-list').editableList({`);
        lines.push(`${ind}  height: 'auto',`);
        lines.push(`${ind}  addItem: function(container, i, opt) {`);
        lines.push(`${ind}    var _vObj = (opt !== null && typeof opt === 'object' && !Array.isArray(opt)) ? opt : null;`);
        lines.push(`${ind}    var _vt = _vObj ? String(_vObj.t || 'str') : 'str';`);
        lines.push(`${ind}    var _vv = _vObj ? String(_vObj.v !== undefined ? _vObj.v : '') : String(opt || '');`);
        lines.push(`${ind}    var inp = $('<input/>', { type: 'text', style: 'width:100%', 'class': 'aoi-val' });`);
        lines.push(`${ind}    container.append(inp);`);
        lines.push(`${ind}    inp.typedInput({ types: ${typedInputTypes('string')} });`);
        lines.push(`${ind}    inp.typedInput('type', _vt);`);
        lines.push(`${ind}    inp.typedInput('value', _vv);`);
        lines.push(`${ind}  },`);
        lines.push(`${ind}  removable:  true,`);
        lines.push(`${ind}  sortable:   true,`);
        lines.push(`${ind}  addButton:  false,`);
        lines.push(`${ind}});`);
        lines.push(`${ind}try {`);
        lines.push(`${ind}  var _${key}_saved = JSON.parse(_${key}_rawJson);`);
        lines.push(`${ind}  var _${key}_items = Array.isArray(_${key}_saved) ? _${key}_saved : [];`);
        lines.push(`${ind}  if (_${key}_items.length === 0) _${key}_items = [{ t: 'str', v: '' }];`);
        lines.push(`${ind}  _${key}_items.forEach(function(item) { $('#${key}-list').editableList('addItem', item); });`);
        lines.push(`${ind}} catch(e) { $('#${key}-list').editableList('addItem', { t: 'str', v: '' }); }`);
        lines.push(`${ind}$('#${key}-list-add').on('click', function(e) { e.preventDefault(); $('#${key}-list').editableList('addItem', { t: 'str', v: '' }); });`);
        lines.push(`${ind}function _${key}_refreshList() {`);
        lines.push(`${ind}  var t = $('#node-input-${keyType}').val() || 'list';`);
        lines.push(`${ind}  var fieldVisible = $('#node-input-${key}').closest('.ep-field-row').is(':visible');`);
        lines.push(`${ind}  if (t === 'list' && fieldVisible) { $('.array-list-row[data-for="${key}"]').show(); }`);
        lines.push(`${ind}  else                              { $('.array-list-row[data-for="${key}"]').hide(); }`);
        lines.push(`${ind}}`);
        lines.push(`${ind}$('#node-input-${key}').on('change', function() { _${key}_refreshList(); });`);
        lines.push(`${ind}_${key}_refreshList();`);
      }
    }
  }

  return lines.join('\n');
}

/**
 * Maps OpenAPI schema type definitions to Node-RED TypedInput widget configurations.
 *
 * TypedInput types serve two purposes:
 *   - How the user directly inputs a value (str / num / bool / list / map, etc.) — determined by schema type
 *   - Where the value comes from at runtime (msg / flow / global / env) — provided universally for all types
 *
 * Centralizing here ensures FieldType additions/changes require only one edit location.
 * Do NOT create a separate function for similar purposes
 * (previously split into apValueTypes, now merged).
 *
 * cf. `defaultTypeStr()` in utils.ts — handles the same FieldType mapping but for
 *     generating initial type strings in the defaults object; kept separate due to
 *     different responsibilities.
 *
 * @param fieldType FieldType value (e.g. 'string', 'number', 'array-of-string').
 * @returns TypedInput types array literal string for use in `typedInput({ types: ... })`.
 */
function typedInputTypes(fieldType: string): string {
  switch (fieldType) {
    case 'number':          return "['num', 'msg', 'flow', 'global', 'env']";
    case 'boolean':         return "['bool', 'msg', 'flow', 'global', 'env']";
    case 'string':          return "['str', 'msg', 'flow', 'global', 'env']";
    case 'binary':
      return "[{ value: 'str', label: 'file path', icon: 'fa fa-file' }, 'msg', 'flow', 'global', 'env']";
    case 'array-of-string': return "[{ value: 'list', label: 'list', icon: 'fa fa-list', hasValue: false }, 'msg', 'flow']";
    case 'additional-properties':
      return "[{ value: 'map', label: 'map', icon: 'fa fa-table', hasValue: false }, 'msg', 'flow', 'global', 'env']";
    default:
      return "['str', 'num', 'bool', 'json', 'msg', 'flow', 'global', 'env']";
  }
}
